### ISSUE TITLE
Export project to DialogFlow format

### ISSUE THREAD

**Issue by Toni-SM** [flow-ai/backlog#147]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
- feature request
 
#### What is the current behavior?
I can only export the project to Flow.AI JSON format

#### What is the expected behavior?
The desire of export the project to other format (example: DialogFlow)

#### What is the motivation/use case for changing the behavior?
Develop the conversation on Flow.AI (more user-friendly) and use with DialogFlow (not so user-friendly)

#### Please tell us about your environment:
- Browser: Firefox 64
- OS: Windows 10

## TODO:
This will be filled out by us (Flow.ai team). Want to colleborate? Let us know on [our Slack channel](https://slack.flow.ai)!

**Comment by Geeza** [comment]
Thank you for the request! Exporting to different formats isn't on our backlog yet
